min_version = "2025.7.7"

[env]
NODE_ENV = "{{ env.NODE_ENV | default(value='development') }}"

# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

[tools]
lazygit = "latest"
neovim = "latest"

[tasks.nvim-config]
description = 'Install nvim config'
run = 'git clone https://github.com/stephen-shopopop/neovim ~/.config/nvim'

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
'''
